### ISSUE TITLE
An error with file concatenation

### ISSUE THREAD

**Issue by bolbatav** [mjsull/chromatiblock#15]
Hello.
I ran the script like this:
`chromatiblock -d ~/beastruns/chromatiblock/raw/ -w ~/beastruns/chromatiblock/tmp -o figure.svg`
and it sad this to me:
```
error: parse error in /home/alexander/beastruns/chromatiblock/tmp/input.fasta on line 1: empty sequence
Traceback (most recent call last):
  File "/Software/chromatiblock", line 1479, in <module>
    block_dict = get_blocks(args.working_directory, name_dict, seq_dict, gene_list, cats)
  File "/Software/chromatiblock", line 562, in get_blocks
    with open(sibel_dir + '/blocks_coords.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alexander/beastruns/chromatiblock/tmp/blocks_coords.txt'
```
The ~/beastruns/chromatiblock/raw/ directory contains 85 separate fasta sequences.
I've checked the input.fasta file and sure enough, it was empty. Then i tried to run it like this:
`chromatiblock -f ~/beastruns/chromatiblock/raw/* --force --keep -w ~/beastruns/chromatiblock/tmp -o figure.svg`
and it failed due to wrong file concatenation.
```
error: parse error in /home/alexander/beastruns/chromatiblock/tmp/input.fasta on line 2: illegal character: >
Traceback (most recent call last):
  File "/home/alexander/miniconda3/envs/chromatiblock/bin/chromatiblock", line 1479, in <module>
    block_dict = get_blocks(args.working_directory, name_dict, seq_dict, gene_list, cats)
  File "/home/alexander/miniconda3/envs/chromatiblock/bin/chromatiblock", line 562, in get_blocks
    with open(sibel_dir + '/blocks_coords.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alexander/beastruns/chromatiblock/tmp/blocks_coords.txt'
```
The sequences were like:
\>0_0
atatata>1_0
tatatata>2_0
etc.

I traced the error back to write_fasta_sibel function and changed line 423 to
`                        out.write(line+'\n')`
Now it works with `-f ~/beastruns/chromatiblock/raw/*`, but `-d ~/beastruns/chromatiblock/raw/` still writes an empty file.

Also, it says 
`No core blocks found. No regions >1000bp were found once in all genomes. Please use more closely related genomes.`
though i set minimum block size to 100, is it ok?

**Comment by mjsull** [comment]
Hi, thanks for picking that up. Chromatiblock was assuming that all FASTA files ended with a newline (which isn't always the case). I've fixed it now. For the -d problem are they using one of the extensions defined by the -e flag?

That error message was hard coded and didn't change no matter what the minimum block size was set to, chromatiblock needs 1 core block bigger than the minimum block size (not 1000bp). So if you saw that error that is why, I've fixed the error message now.
